### ISSUE TITLE
Maestro Windows Install Instructions Seem Wrong

### ISSUE THREAD

**Issue by crutchcorn** [mobile-dev-inc/maestro-docs#22]
Under the "Android SDK" setup instructions for Windows:

https://maestro.mobile.dev/getting-started/installing-maestro/windows#lets-set-you-up-to-use-android-in-your-freshly-installed-wsl2

We're told to move everything out of `cmdline-tools` and into a directory called `tools`. However, after doing so (and running `sdkmanager --list`), we find ourselves with the following error:

```
 ✘ 💡   ~/Android 
↳ sdkmanager --install "platform-tools"
Error: Could not determine SDK root.
Error: Either specify it explicitly with --sdk_root= or move this package into its expected location: <sdk>/cmdline-tools/latest/
```

If I instead migrate the `cmdline-tools` directory to `cmdline-tools/latest` (rather than `tools`), I get the proper behavior out-of-the-box.

I'm happy to fix the docs if this is something y'all would like :)

**Comment by axelniklasson** [comment]
Thanks for raising this @crutchcorn -- docs have been updated [here](https://maestro.mobile.dev/getting-started/installing-maestro/windows), let us know if there is something else missing :) Thanks!
