### ISSUE TITLE
[Flutter] Test Google, Facebook or Apple Auth

### ISSUE THREAD

**Issue by shrijanRegmi** [mobile-dev-inc/maestro-docs#41]
I have a Flutter application that has Google, Facebook and Apple auth. On my emulators, I can easily test them. But how does the emulators on the cloud test these social authentication methods?

**Comment by niklaskroe** [comment]
How do you test them on your local emulator?

**Comment by bartekpacia** [comment]
You have to sign manually. You can extract this logic into a subflow.
