### ISSUE TITLE
[Expo] maestro + expo 50

### ISSUE THREAD

**Issue by raulzilla** [mobile-dev-inc/maestro-docs#42]
Hello!

I'm working on a react-native and expo project, after a new expo 50 update it is necessary to use jdk 17, but maestro requests the use of jdk 11, I know that this is not a problem with maestro and that he only provides support to react-native, but I was able to use it safely before that, does anyone know if there is any kind of troubleshooting for this scenario?

**Comment by Fishbowler** [comment]
I've got Java 17 and not hit problems in executing Maestro.

For _developing_ in the Maestro codebase, I recently contributed a `.jenv` file so that it uses Java 11 in that project only, leaving me to use 17 everywhere else on this machine.

**Comment by raulzilla** [comment]
Thanks you @Fishbowler for your help
