### ISSUE TITLE
Add retryTapIfNoChange to tapOn

### ISSUE THREAD

**Issue by Fishbowler** [mobile-dev-inc/maestro-docs#49]
`retryTapIfNoChange` is mentioned in [Known Issues](https://maestro.mobile.dev/troubleshooting/known-issues#android-accidental-double-tap), but not in [tapOn](https://maestro.mobile.dev/api-reference/commands/tapon).

**Comment by bartekpacia** [comment]
hey @Fishbowler, good catch. Thank you! would you be up to make a PR for it?

**Comment by Fishbowler** [comment]
Nice one @niklaskroe :heart:
