### ISSUE TITLE
Make "assertVisible" find part of a text

### ISSUE THREAD

**Issue by K0n2t1** [mobile-dev-inc/maestro-docs#66]
In my React Native application the test should open an article and check it's content being visible afterwards. I can't make it work yet, since it seems to only succeed when the string of assertVisible is the complete content of a screen element. I am not able to provide the whole article text in the yaml file. Also pasting the whole article in the test yaml makes it unreadable and
the content can contain text styling, line breaks and more.

My understanding of something being visible is fullfilled, if it is visible as part of a bigger text:

- assertVisible: "World"
This should be true if an element containing "Hello World!" is visible.

Would be great to make this the standard behaviour. If necessary you can possibly add an option to use the current behaviour.

Best regards.

**Comment by Fishbowler** [comment]
Is this one for the maestro repo? I don't see a documentation specific problem here.
