### ISSUE TITLE
copyTextFrom

### ISSUE THREAD

**Issue by ALexYuRcho-wq** [mobile-dev-inc/maestro-docs#88]
Hello! 
Tell me how the command copyTextFrom works correctly.
I call the command by passing the element ID into it, but when inserting it into a field, it inserts not the text, but the name of the element ID. 
The problem is either in the correct ID for the elements or I’m doing something wrong. Help me figure it out

Example:

copyTextFrom:
  id: MainFromEditorialText

<img width="264" alt="image" src="https://github.com/user-attachments/assets/4b156f85-3a5a-4f09-a7ef-56149571af0f">

**Comment by bartekpacia** [comment]
This issue belongs to the Maestro repo, not here.
